Smt building
ebukreev/symbolic-execution-2024 pull request #1
Opened 2024-10-12 09:35 UTC by ebukreev

Сделал структуры для символьных выражений и построение смт на их основе. В тестах для каждого тестового файла руками строятся символьные выражения, а затем по ним автоматически строится смт.

Брал эти биндинги для z3: https://github.com/aclements/go-z3/tree/master Но в них не оказалось апи для работы с assumptions и unsat_core, поэтому пришлось их положить локально и немного дописать.

2024-10-23 13:55 UTC, CaelmBleidd requested changes
Есть вопросы с инкрементальностями, глянь, пожалуйста, и прокомментируй или поправь

2024-10-23 13:55 UTC, CaelmBleidd commented on complex_test.go
> +		solver.SmtSolver.Assert(res.(z3.Float).Eq(expressionSmt[0].(z3.Float)))
Эта секция здесь лишняя?

2024-10-23 13:55 UTC, CaelmBleidd commented on softconstraints_test.go
> +			solver.SmtSolver.Pop()
Тут ты дрогнул всё, что было добавлено после последнего пуша. Например, если были бы какие-то другие софт констреинты, их бы ты тоже дропнул. Но и в целом кажется, что излишне делать push перед тем как проверять софты, так запаришься пушить попать. Идея в том, чтобы выкидывать только те ограничения, которые тебе не нужны. По крайней мере в си апи z3 вроде была возможность вызывать check(assumption), при этом не доливая их каждый раз в солвер, хотелось бы увидеть что-от похожее

2024-10-23 13:55 UTC, CaelmBleidd commented on push_pop_test.go
> +			continue
Зачем нам что-то продолжать, если мы дошли до unsat состояния? Судя по ограчению выше, если оно не выполняется, то надо исключение вообще кидать, а не продолжать

2024-10-23 13:55 UTC, CaelmBleidd commented on push_pop_test.go
> +		solver.SmtSolver.Push()
Цикл константный, в некотором смысле, в нем нет никаких важных развилок, которые могли бы повлиять на рост сложности решения. Поэтому нет смысла добавлять фрейм на каждую итерацию, мы просто не сможем переиспользовать никакую информацию с прошлых шагов, потому что никаких рассуждений не делалось, а лишние действия совершаем

2024-10-23 13:55 UTC, CaelmBleidd commented on push_pop_test.go
> +	mod := &Equals{&BinaryOperation{result, &Literal[int]{2}, Mod}, &Literal[int]{0}}
В то же время вот это выражение имело смысл записать после цикла. Итерации цикла не приносят особо никакой дополнительной информации между собой, но здесь возникает деление потока управления -- они оба используют одну и ту же информацию из солвера, поэтому здесь перед этим имело бы смысл запушить фрейм. 

Таким образом ты добавил бы все необходимые "общие" ограничения в цикле в один фрейм, затем запушил, проверил одну ветку, запопал, проверил другую. Профит

2024-10-24 06:19 UTC, ebukreev commented on complex_test.go
> +		solver.SmtSolver.Assert(res.(z3.Float).Eq(expressionSmt[0].(z3.Float)))
Нет, она используется для TestComplexComparison, когда результат функции float

2024-10-24 07:12 UTC, ebukreev commented on softconstraints_test.go
> +			solver.SmtSolver.Pop()
Поправил, добавил апи для check(assumption)

2024-10-24 07:12 UTC, ebukreev commented on push_pop_test.go
> +			continue
Поправил

2024-10-24 07:12 UTC, ebukreev commented on push_pop_test.go
> +		solver.SmtSolver.Push()
Поправил, переделал тест

2024-10-24 07:12 UTC, ebukreev commented on push_pop_test.go
> +	mod := &Equals{&BinaryOperation{result, &Literal[int]{2}, Mod}, &Literal[int]{0}}
Поправил

2024-10-29 08:35 UTC, CaelmBleidd approved these changes

2024-10-29 08:35 UTC, CaelmBleidd commented on softconstraints_test.go
> +		t.Fatal("FALSE UNSAT")
Пайплайн всё ещё не такой, каким я хотел бы его видеть, но можешь переделать уже в рамках интерпретатора. 

Глобально идея в следующем: у тебя есть набор жёстких ограничений PC и набор "мягких" ограничений SC: sc1, sc2, sc3, ...
Мягкие ограничения могут вступать в ограничения, тогда в unsatcore ты увидишь информацию о том, что кто-то из них конфликтует. Например, sc1 и sc2. Тебе требуется автоматически найти это ограничение в своем наборе и исключить их, потому что это итеративный процесс -- дальше ты снова можешь получить какой-то другой unsat с другими огрангичениями, и тд

2024-10-31 06:06 UTC, merged